// demo/react/src/windows/GuideApp.tsx
import React from 'react'

const s = {
  root: { height: '100%', display: 'flex', flexDirection: 'column', background: 'var(--dp-window-body-bg,#13131f)', color: 'var(--dp-window-body-color,#e0e0f0)', padding: '16px', overflowY: 'auto', fontFamily: 'system-ui, sans-serif', fontSize: 13, boxSizing: 'border-box', gap: 10 } as React.CSSProperties,
  h1: { margin: '0 0 4px', fontSize: 15, fontWeight: 700 } as React.CSSProperties,
  card: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 8, padding: '12px 14px' } as React.CSSProperties,
  label: { fontSize: 10, textTransform: 'uppercase' as const, letterSpacing: '0.08em', color: '#3b82f6', fontWeight: 600, marginBottom: 8 },
  code: { display: 'block', background: 'rgba(0,0,0,0.3)', borderRadius: 6, padding: '8px 10px', fontFamily: 'monospace', fontSize: 11, color: '#93c5fd', whiteSpace: 'pre' as const, overflowX: 'auto' as const, margin: 0 },
  hint: { margin: '8px 0 0', fontSize: 11, color: 'rgba(255,255,255,0.5)', lineHeight: 1.5 },
  item: { display: 'flex', gap: 10, fontSize: 12, padding: '4px 0' } as React.CSSProperties,
}

export default function GuideApp() {
  return (
    <div style={s.root}>
      <h2 style={s.h1}>⚛️ React 整合指南</h2>

      <div style={s.card}>
        <div style={s.label}>架構說明</div>
        <p style={s.hint}>DeskPane Desktop 提供桌面殼層（圖示 + Dock），React 元件透過 createPortal 渲染進視窗 body。視窗最小化時 DOM 仍保留，useState 狀態不丟失。</p>
      </div>

      <div style={s.card}>
        <div style={s.label}>開窗方式</div>
        <code style={s.code}>{`wm.open({
  id: 'app-guide',
  title: 'React 指南',
  slotType: 'react',  // 留空 body
  content: null,
})`}</code>
      </div>

      <div style={s.card}>
        <div style={s.label}>Portal 注入</div>
        <code style={s.code}>{`{windows.map(w =>
  createPortal(<w.component />, w.bodyEl, w.id)
)}`}</code>
        <p style={s.hint}>最小化時視窗 body 隱藏但不卸載，React 狀態自動保留。</p>
      </div>

      <div style={s.card}>
        <div style={s.label}>示範元件</div>
        {[
          ['📝', '文字編輯器 — useState 控制內容，最小化後保留'],
          ['✅', '待辦清單 — useState 陣列，展示 React 響應式更新'],
          ['🔢', '計數器 — 最小化後數值不重置（Portal 保留 DOM）'],
          ['🧮', '計算機 — useState + 事件處理'],
        ].map(([icon, desc]) => (
          <div key={icon as string} style={s.item}>
            <span style={{ fontSize: 14, flexShrink: 0 }}>{icon}</span>
            <span style={{ color: 'rgba(255,255,255,0.65)', lineHeight: 1.5 }}>{desc}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// demo/vue/src/windows/GuideApp.vue
<template>
  <div class="guide-app">
    <h2 class="title">🧩 Vue 3 整合指南</h2>

    <section class="card">
      <div class="card-label">架構說明</div>
      <p class="hint">DeskPane Desktop 提供桌面殼層（圖示 + Dock），Vue 3 元件透過 <code>Teleport</code> 渲染進視窗 body。</p>
    </section>

    <section class="card">
      <div class="card-label">開窗方式</div>
      <pre class="code">wm.open({
  id: 'app-guide',
  title: 'Vue 指南',
  slotType: 'vue',   // 留空 body
  content: null,
})</pre>
    </section>

    <section class="card">
      <div class="card-label">Teleport 注入</div>
      <pre class="code">&lt;Teleport :to="win.bodyEl"&gt;
  &lt;KeepAlive&gt;
    &lt;component :is="win.component" /&gt;
  &lt;/KeepAlive&gt;
&lt;/Teleport&gt;</pre>
      <p class="hint">KeepAlive 確保最小化後元件狀態完整保留。</p>
    </section>

    <section class="card">
      <div class="card-label">示範元件</div>
      <div class="api-list">
        <div v-for="item in items" :key="item.desc" class="api-item">
          <span class="api-icon">{{ item.icon }}</span>
          <span class="api-desc">{{ item.desc }}</span>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
const items: Array<{ icon: string; desc: string }> = [
  { icon: '📝', desc: '文字編輯器 — v-model 雙向綁定，KeepAlive 保留狀態' },
  { icon: '✅', desc: '待辦清單 — ref 陣列響應式操作' },
  { icon: '🔢', desc: 'Keep-Alive 計數器 — 最小化後數值不重置' },
  { icon: '🧮', desc: '計算機 — computed + template 事件處理' },
]
</script>

<style scoped>
.guide-app {
  height: 100%;
  overflow-y: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  background: var(--dp-window-body-bg, #13131f);
  color: var(--dp-window-body-color, #e0e0f0);
  font-family: 'Segoe UI', system-ui, sans-serif;
}
.title { margin: 0 0 4px; font-size: 15px; font-weight: 700; }
.card {
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 8px;
  padding: 12px 14px;
}
.card-label {
  font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em;
  color: #3b82f6; font-weight: 600; margin-bottom: 8px;
}
.code {
  margin: 0; padding: 8px 10px; background: rgba(0,0,0,0.3);
  border-radius: 6px; font-size: 11px;
  font-family: 'Cascadia Code', 'Consolas', monospace;
  color: #93c5fd; white-space: pre-wrap; word-break: break-all;
}
.hint { margin: 8px 0 0; font-size: 11px; color: rgba(255,255,255,0.5); line-height: 1.5; }
.hint code { background: rgba(255,255,255,0.1); padding: 1px 5px; border-radius: 3px; }
.api-list { display: flex; flex-direction: column; gap: 6px; }
.api-item { display: flex; gap: 10px; align-items: baseline; font-size: 12px; }
.api-icon { font-size: 14px; flex-shrink: 0; }
.api-desc { color: rgba(255,255,255,0.65); line-height: 1.5; }
</style>
