// demo/vue/src/windows/CalcApp.vue
<template>
  <div class="calc-app">
    <div class="display">{{ display }}</div>
    <div class="grid">
      <button
        v-for="k in keys" :key="k"
        class="key"
        :class="{ op: isOp(k), fn: isFn(k) }"
        @click="press(k)"
      >{{ k }}</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const display = ref('0')
let expr = ''

const keys = ['C','±','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','⌫','=']

const isOp = (k: string) => '÷×−+='.includes(k)
const isFn = (k: string) => 'C±%'.includes(k)

function press(k: string) {
  if (k === 'C') { expr = ''; display.value = '0'; return }
  if (k === '=') {
    try {
      const r = Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))()
      display.value = String(r); expr = String(r)
    } catch { display.value = '錯誤'; expr = '' }
    return
  }
  if (k === '⌫') { expr = expr.slice(0,-1); display.value = expr || '0'; return }
  if (k === '±') {
    try {
      const v = -Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))()
      display.value = String(v); expr = String(v)
    } catch {} return
  }
  if (k === '%') {
    try {
      const v = Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))() / 100
      display.value = String(v); expr = String(v)
    } catch {} return
  }
  expr += k; display.value = expr
}
</script>

<style scoped>
.calc-app {
  height: 100%; display: flex; flex-direction: column; gap: 10px;
  padding: 12px; box-sizing: border-box;
  background: var(--dp-window-body-bg, #13131f);
  color: var(--dp-window-body-color, #e0e0f0);
}
.display {
  width: 100%; padding: 10px; font-size: 22px; text-align: right;
  border-radius: 6px; border: 1px solid rgba(255,255,255,0.12);
  background: rgba(255,255,255,0.06); min-height: 48px;
  word-break: break-all;
}
.grid {
  display: grid; grid-template-columns: repeat(4, 1fr); gap: 6px; flex: 1;
}
.key {
  padding: 0; font-size: 16px; font-weight: 500; border-radius: 8px;
  border: 1px solid rgba(255,255,255,0.08); cursor: pointer;
  background: rgba(255,255,255,0.08); color: inherit;
  transition: opacity .1s;
}
.key:active { opacity: 0.65; }
.key.op { background: #ff9500; color: #fff; border-color: #ff9500; }
.key.fn { background: rgba(255,255,255,0.18); }
</style>

// demo/react/src/windows/CalcApp.tsx
import React, { useState } from 'react'

const KEYS = ['C','±','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','⌫','=']

export default function CalcApp() {
  const [display, setDisplay] = useState('0')
  const exprRef = React.useRef('')

  function press(k: string) {
    const expr = exprRef.current
    if (k === 'C') { exprRef.current = ''; setDisplay('0'); return }
    if (k === '=') {
      try {
        const r = Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))()
        exprRef.current = String(r); setDisplay(String(r))
      } catch { exprRef.current = ''; setDisplay('錯誤') }
      return
    }
    if (k === '⌫') { exprRef.current = expr.slice(0,-1); setDisplay(exprRef.current || '0'); return }
    if (k === '±') {
      try {
        const v = -Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))()
        exprRef.current = String(v); setDisplay(String(v))
      } catch {} return
    }
    if (k === '%') {
      try {
        const v = Function('return ' + expr.replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-'))() / 100
        exprRef.current = String(v); setDisplay(String(v))
      } catch {} return
    }
    exprRef.current = expr + k; setDisplay(exprRef.current)
  }

  const isOp = (k: string) => '÷×−+='.includes(k)
  const isFn = (k: string) => 'C±%'.includes(k)

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: 10, padding: 12, boxSizing: 'border-box', background: 'var(--dp-window-body-bg,#13131f)', color: 'var(--dp-window-body-color,#e0e0f0)' }}>
      <div style={{ padding: 10, fontSize: 22, textAlign: 'right', borderRadius: 6, border: '1px solid rgba(255,255,255,0.12)', background: 'rgba(255,255,255,0.06)', minHeight: 48, wordBreak: 'break-all' }}>
        {display}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 6, flex: 1 }}>
        {KEYS.map(k => (
          <button
            key={k}
            onClick={() => press(k)}
            style={{
              padding: 0, fontSize: 16, fontWeight: 500, borderRadius: 8,
              border: '1px solid rgba(255,255,255,0.08)', cursor: 'pointer',
              background: isOp(k) ? '#ff9500' : isFn(k) ? 'rgba(255,255,255,0.18)' : 'rgba(255,255,255,0.08)',
              color: isOp(k) ? '#fff' : 'inherit',
            }}
          >{k}</button>
        ))}
      </div>
    </div>
  )
}
